### ISSUE TITLE
Not exporting types

### ISSUE THREAD

**Issue by orta** [orta/danger-plugin-yarn#1]

**Comment by glensc** [comment]
Can you be specific, about what this issue stands for?

change to export only `export default function yarn(options?: Options): Promise<void>;` ?

**Comment by glensc** [comment]
@orta can you respond?

**Comment by orta** [comment]
it was 5 years ago, I assume that it was that the .d.ts file wasn't shipped and it look like it is now: https://unpkg.com/browse/danger-plugin-yarn@1.5.1/dist/

Looks like all of the sub functions are exported fine, so this can probably be closed

**Comment by glensc** [comment]
How do you feel about cleaning up the exports, to only export  only `default yarn`? as the other methods need very specific input, so calling them directly outside this plugin is probably not ever used.

and if you need to disable some functionality there are already options for these.

in other words calling those directly not needed, but can be achieved by calling via default export.
