### ISSUE TITLE
Seeing double notes when adding a dep

### ISSUE THREAD

**Issue by orta** [orta/danger-plugin-yarn#12]
<img width="556" alt="screen shot 2017-09-26 at 9 08 25 am" src="https://user-images.githubusercontent.com/49038/30861935-47860b56-a29a-11e7-80f0-a71d964c3de5.png">

<img width="902" alt="screen shot 2017-09-26 at 9 08 30 am" src="https://user-images.githubusercontent.com/49038/30861936-48e829b6-a29a-11e7-91e4-1f2121c74f99.png">

**Comment by fbartho** [comment]
This ticket is out-of-date or resolved!

**Comment by glensc** [comment]
@orta close
