### ISSUE TITLE
Add support for a different default registry and for scoped registries

### ISSUE THREAD

**Issue by sebinsua** [orta/danger-plugin-yarn#17]
It would be good if this package had support for a different default registry and additional scoped registries.

This would help users in an 'Enterprise' setting. Especially if their private packages do not exist on `registry.npmjs.org` at all.

**Comment by orta** [comment]
Sure, yeah, makes sense - I don't have anything like this to test it on, so I'm afraid this one is on you 👍

**Comment by glensc** [comment]
For the test you could use `registry.yarnpkg.com`, it's just a proxy:
- https://github.com/yarnpkg/yarn/issues/889#issuecomment-253237639
