### ISSUE TITLE
Merge in existing dependabot PR's

### ISSUE THREAD

**Issue by IRESS-Chris-Hill** [orta/danger-plugin-yarn#37]
Hi, 

Could the existing dependabot PR's be merged into main branch please? We're currently triaging our own dependabot issues and have found that node-fetch is being flagged

Kindest Regards and Many Thanks

**Comment by glensc** [comment]
Some node-fetch was merged with #28

**Comment by orta** [comment]
thanks for the reminder, merged that one and disabled dependabot - folks will send PRs for useful dep updates 👍🏻

**Comment by glensc** [comment]
You can re-configure dependabot to send only critical updates.

**Comment by orta** [comment]
Never been worth it for me, nearly always noise. People who care will send updates for updates which are actually critical.
