### ISSUE TITLE
Feature Request: Feature-Flags to disable the @types warning

### ISSUE THREAD

**Issue by fbartho** [orta/danger-plugin-yarn#41]
We're using [manypkg](https://github.com/Thinkmill/manypkg) in a monorepo, and we're just getting around to adding DangerJS to this project. manypkg states that there's no distinction between deps/devDeps in the top-level package.json, so it automatically collapses `devDependencies` into `dependencies`

This trips danger-plugin-yarn's `@types` warning, and I want to suppress that while keeping manypkg.

It looks like the relevant code is here: https://github.com/orta/danger-plugin-yarn/blob/0b636cb0bf3e3bb8664569a848b5b80e585663dd/src/index.ts#L218-L243 and I'm happy to submit a PR implementing this if you're okay with it. I'd prefer not to have to publish my own copy of danger-plugin-yarn with such a trivial feature.

## Questions

A. would you object to feature-flags on the plugin's `Options` object to enable / disable this feature?
B. if no, would you like it to be something like `disableTypesInDepsCheck?: boolean` ? -- Some other naming scheme?
C. Do you want each of the 4 checks to have a feature flag while I'm in there?

Standing by to submit a PR with tests once I hear from you @orta :)

**Comment by orta** [comment]
Yeah, I'm cool with the `Options` type taking a 'disableXY' for those sub-functions 👍🏻
