### ISSUE TITLE
Feature Request: Monorepo New Dependency in multiple packages should only have 1 info section

### ISSUE THREAD

**Issue by fbartho** [orta/danger-plugin-yarn#43]
When you add a dependency to multiple packages, danger-plugin-yarn reports about it multiple-times

![TriplicateDeps](https://user-images.githubusercontent.com/209712/142499092-6ca74a08-5b0e-4640-b34c-de7f417b671e.png)

Suggested feature: report only once per dependency, but if there are duplicates then add the path to the package.json it was added to.

I totally don't mind providing a PR to do this, but first I wanted to check:
- if you want this feature?
- where in the the message would you want this to live / what wording would make sense?

eg. `<package-name> was added to 3 package.json files: 'apps/app1/package.json', 'apps/app2/package.json', libs/lib1/package.json'`

**Comment by orta** [comment]
Yeah, that should deduce and I agree with the message - maybe the title can change to include the workspace names?

**Comment by fbartho** [comment]
@orta I have a branch almost ready to submit a PR for, but when I rendered the `danger-plugin-yarn` comment on GitHub as we discussed above, it looked kinda funky because it got resized to be part of the heading.

Here are some of the alternatives I played around with.:

<details><summary>Option A. - next to the package title</summary>

<h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a> Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code></h2>
<p>Author: Orta Therox</p>
<p>Description: Unit tests for Team Culture</p>
<p>Homepage: <a href="https://github.com/danger/danger-js#readme">https://github.com/danger/danger-js#readme</a></p>
[snip]</details>

<details><summary>Option B. - next line</summary>
<h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h2>
<p>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code></p>
<p>Author: Orta Therox</p>
<p>Description: Unit tests for Team Culture</p></summary>
<p>Homepage: <a href="https://github.com/danger/danger-js#readme">https://github.com/danger/danger-js#readme</a></p>
[snip]</details>

<details><summary>Option C. - unordered list</summary>
<h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h2><ul>
<li>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code></li>
<li>Author: Orta Therox</li>
<li>Description: Unit tests for Team Culture</li>
<li>Homepage: <a href="https://github.com/danger/danger-js#readme">https://github.com/danger/danger-js#readme</a></li>
</ul>
[snip]</details>

<details><summary>:star: Option D. - Table w/Rowspan</summary>
Variant A. Rowspan on Right
<table>
<tr><td><h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h2></td><td rowspan=4>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code></td></tr>
<tr><td>Author: Orta Therox</td></tr>
<tr><td>Description: Unit tests for Team Culture</td></tr>
<tr><td>Homepage: <a href="https://github.com/danger/danger-js#readme">https://github.com/danger/danger-js#readme</a></td></tr>
</table>
Variant B. Metadata on Right
<table>
<tr><td><h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h2></td>
<td>Author: Orta Therox</td></tr>
<tr><td rowspan=2>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code></td>
<td>Description: Unit tests for Team Culture</td></tr>
<tr><td>Homepage: <a href="https://github.com/danger/danger-js#readme">https://github.com/danger/danger-js#readme</a></td></tr>
</table>
</details>

<details><summary>Option E. - Table-just-heading</summary>
<table>
<tr><td><h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h2></td><td rowspan=4>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code></td></tr>
</table>
<p>Author: Orta Therox</p>
<p>Description: Unit tests for Team Culture</p></summary>
<p>Homepage: <a href="https://github.com/danger/danger-js#readme">https://github.com/danger/danger-js#readme</a></p>
[snip]</details>

I'm personally partial to either `Option C: unordered list` or `Option D: Table w/ rowspan`

Which option would you like me to use, and/or how would you like me to handle this?

**Comment by fbartho** [comment]
I could also be happy with `Option E` where *just the heading* is a Table, but also changing the meta-data paragraphs to unordered list bullets (to tighten up the interline spacing)

<table>
<tr><td><h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h2></td><td rowspan=4>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code></td></tr>
</table><ul>
<li>Author: Orta Therox</li>
<li>Description: Unit tests for Team Culture</li></summary>
<li>Homepage: <a href="https://github.com/danger/danger-js#readme">https://github.com/danger/danger-js#readme</a></li></ul>

**Comment by fbartho** [comment]
I've updated my comment to add an even more compact Variant B of `Option D.` where the metadata is on the right, and the used-in-package.json list is below the heading.

**Comment by orta** [comment]
Yah, D seems pretty solid to me.

**Comment by fbartho** [comment]
# Full Prototype A.
<table width="100%">
<tr><td> <h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h2> </td><td> <i>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code><i> </td></tr>
<tr><td> <b>Author:</b> <wbr/>Orta Therox </td><td> <b>Description:</b> <wbr/>Unit tests for Team Culture </td></tr>
<tr><td> <b>License:</b> <wbr/>MIT </td><td> <b>Homepage:</b> <wbr/><a href="https://github.com/danger/danger-js#readme">https://<wbr/>github.com/<wbr/>danger/<wbr/>danger-js#readme</a> </td></tr>
<tr><td> <b>Updated:</b> <wbr/>over 4 years ago </td><td> <b>Created:</b> <wbr/>over 5 years ago </td></tr>
<tr><td colspan="2"> <b>Keywords:</b> <wbr/>danger,ci </td></tr>
<tr><td> <b>Releases:</b> <wbr/>45 </td><td> <b>Maintainers:</b> <wbr/>3 </td></tr>
<tr><td colspan="3"> <b>Direct <wbr/>Deps:</b> <wbr/><a href='https://www.npmjs.com/package/babel-polyfill'><code>babel-polyfill</code></a>, <wbr/><a href='https://www.npmjs.com/package/chalk'><code>chalk</code></a>, <wbr/><a href='https://www.npmjs.com/package/commander'><code>commander</code></a>, <wbr/><a href='https://www.npmjs.com/package/debug'><code>debug</code></a>, <wbr/><a href='https://www.npmjs.com/package/github'><code>github</code></a>, <wbr/><a href='https://www.npmjs.com/package/jest-config'><code>jest-config</code></a>, <wbr/><a href='https://www.npmjs.com/package/jest-environment-node'><code>jest-environment-node</code></a>, <wbr/><a href='https://www.npmjs.com/package/jest-runtime'><code>jest-runtime</code></a>, <wbr/><a href='https://www.npmjs.com/package/jsome'><code>jsome</code></a>, <wbr/><a href='https://www.npmjs.com/package/jsonpointer'><code>jsonpointer</code></a>, <wbr/><a href='https://www.npmjs.com/package/lodash.find'><code>lodash.find</code></a>, <wbr/><a href='https://www.npmjs.com/package/lodash.includes'><code>lodash.includes</code></a>, <wbr/><a href='https://www.npmjs.com/package/lodash.isobject'><code>lodash.isobject</code></a>, <wbr/><a href='https://www.npmjs.com/package/lodash.keys'><code>lodash.keys</code></a>, <wbr/><a href='https://www.npmjs.com/package/node-fetch'><code>node-fetch</code></a>, <wbr/><a href='https://www.npmjs.com/package/parse-diff'><code>parse-diff</code></a>, <wbr/><a href='https://www.npmjs.com/package/rfc6902'><code>rfc6902</code></a>, <wbr/><a href='https://www.npmjs.com/package/voca'><code>voca</code></a>, <wbr/><a href='https://www.npmjs.com/package/dtslint'><code>dtslint</code></a> </td></tr>
</table>
    
<details>
<summary><code>README</code></summary></br>

[![npm](https://img.shields.io/npm/v/danger.svg)](https://www.npmjs.com/package/danger)
[![Build Status](https://travis-ci.org/danger/danger-js.svg?branch=master)](https://travis-ci.org/danger/danger-js)
[![Build Status](https://ci.appveyor.com/api/projects/status/ep5hgeox3lbc5c7f?svg=true)](https://ci.appveyor.com/project/orta/danger-js/branch/master)

Danger on Node, wonder what's going on? see [VISION.md](VISION.md)

*Welcome!*

So, what's the deal? Well, right now Danger JS does a lot of the simpler parts of [the Ruby version](http://danger.systems).
You can look at [Git](https://github.com/danger/danger-js/blob/master/source/dsl/GitDSL.ts) metadata, or [GitHub](https://github.com/danger/danger-js/blob/master/source/dsl/GitHubDSL.ts) metadata on Travis CI, Circle CI, Semaphore, Jenkins, Docker Cloud, surf-build, Codeship, Drone, or Buildkite.

[...snipped...]

</details>
(testing for legibility)

**Comment by orta** [comment]
Swiching the dependency name from a h3 -> h2 will get rid of the extra underline, bu that looks great!

**Comment by fbartho** [comment]
In the 1-liner case, that makes the baselines look offset:
<table>
<tr><td><h3><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h3></td><td rowspan=4>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code></td></tr>
</table>

But I’m fine either way! Your call! — the PR is ready :)
